/**
 * This file is generated by Amplify CLI.
 */
export type AmplifyDependentResourcesAttributes = {
  hosting: {
    S3AndCloudFront: {
      HostingBucketName: "string";
      WebsiteURL: "string";
      CloudFrontDistributionID: "string";
      Region: "string";
    };
  };
};
