import crypto from "node:crypto";
import type { ScaffoldedFile } from "./scaffold";
import { decrypt, encrypt, hasSecretKey } from "./crypto";
import type { DeployTarget, Project, SiteAccessMode } from "./types";

export const SITE_ACCESS_GATE_USER = "lp";
export const UNSUPPORTED_ACCESS_TEMPLATES = new Set(["c3-next", "c3-astro"]);

export type WranglerConfigRef =
  | { path: "wrangler.toml"; content: string }
  | { path: "wrangler.jsonc"; content: string };

export function siteAccessSupported(templateId?: string): boolean {
  if (!templateId) return false;
  return !UNSUPPORTED_ACCESS_TEMPLATES.has(templateId);
}

export function generateAccessKey(): string {
  return crypto.randomBytes(18).toString("base64url");
}

export async function siteAccessKeyForProject(project: Project): Promise<string | null> {
  if (project.siteAccessKeyEnc) {
    return decrypt(project.siteAccessKeyEnc).catch(() => null);
  }
  return project.siteAccessKey ?? null;
}

export async function persistSiteAccessKey(
  project: Project,
  key: string
): Promise<Partial<Project>> {
  if (hasSecretKey()) {
    const siteAccessKeyEnc = await encrypt(key).catch(() => undefined);
    if (siteAccessKeyEnc) {
      return { siteAccessKeyEnc, siteAccessKey: undefined };
    }
  }
  return { siteAccessKey: key, siteAccessKeyEnc: undefined };
}

function escapeRealm(realm: string): string {
  return realm.replace(/["\\]/g, "");
}

// ── Gate templates ───────────────────────────────────────────────────────────

type GateInput = { key: string; realm: string };

function jsCheckAuth(): string {
  return `function checkAuth(request) {
  const header = request.headers.get("Authorization") ?? "";
  if (!header.startsWith("Basic ")) return false;
  let decoded = "";
  try {
    decoded = atob(header.slice(6));
  } catch {
    return false;
  }
  const sep = decoded.indexOf(":");
  if (sep === -1) return false;
  const user = decoded.slice(0, sep);
  const pass = decoded.slice(sep + 1);
  if (user !== GATE_USER || pass.length !== GATE_KEY.length) return false;
  let diff = 0;
  for (let i = 0; i < pass.length; i++) diff |= pass.charCodeAt(i) ^ GATE_KEY.charCodeAt(i);
  return diff === 0;
}`;
}

function tsCheckAuth(): string {
  return `function checkAuth(request: Request): boolean {
  const header = request.headers.get("Authorization") ?? "";
  if (!header.startsWith("Basic ")) return false;
  let decoded = "";
  try {
    decoded = atob(header.slice(6));
  } catch {
    return false;
  }
  const sep = decoded.indexOf(":");
  if (sep === -1) return false;
  const user = decoded.slice(0, sep);
  const pass = decoded.slice(sep + 1);
  if (user !== GATE_USER || pass.length !== GATE_KEY.length) return false;
  let diff = 0;
  for (let i = 0; i < pass.length; i++) diff |= pass.charCodeAt(i) ^ GATE_KEY.charCodeAt(i);
  return diff === 0;
}`;
}

function unauthorized(): string {
  return `function unauthorized() {
  return new Response("Unauthorized", {
    status: 401,
    headers: { "WWW-Authenticate": \`Basic realm="\${GATE_REALM}"\` },
  });
}`;
}

function workerGateTs({ key, realm }: GateInput, entry: string): string {
  return `// Auto-generated by Launchpad — site access gate. Do not edit manually.
const GATE_USER = "${SITE_ACCESS_GATE_USER}";
const GATE_KEY = "${key}";
const GATE_REALM = "${escapeRealm(realm)}";
${tsCheckAuth()}
${unauthorized()}
type GateApp = {
  fetch(request: Request, env?: unknown, ctx?: unknown): Promise<Response> | Response;
};
const appPromise = import("./${entry}");
export default {
  async fetch(request: Request, env?: unknown, ctx?: unknown): Promise<Response> {
    if (!checkAuth(request)) return unauthorized();
    const app = (await appPromise).default as unknown as GateApp;
    return app.fetch(request, env, ctx);
  },
};
`;
}

function workerGateJs({ key, realm }: GateInput, entry: string): string {
  return `// Auto-generated by Launchpad — site access gate. Do not edit manually.
const GATE_USER = "${SITE_ACCESS_GATE_USER}";
const GATE_KEY = "${key}";
const GATE_REALM = "${escapeRealm(realm)}";
${jsCheckAuth()}
${unauthorized()}
const appPromise = import("./${entry}");
export default {
  async fetch(request, env, ctx) {
    if (!checkAuth(request)) return unauthorized();
    const app = (await appPromise).default;
    return app.fetch(request, env, ctx);
  },
};
`;
}

function pythonGate({ key, realm }: GateInput, entry: string): string {
  return `# Auto-generated by Launchpad — site access gate. Do not edit manually.
import base64
from workers import Response
from ${entry} import Default as App

GATE_USER = "${SITE_ACCESS_GATE_USER}"
GATE_KEY = "${key}"
GATE_REALM = "${escapeRealm(realm)}"


class Default(App):
    async def _authorized(self, request):
        header = request.headers.get("Authorization") or ""
        if not header.startswith("Basic "):
            return False
        try:
            decoded = base64.b64decode(header[6:]).decode("utf-8")
        except Exception:
            return False
        user, sep, pwd = decoded.partition(":")
        if not sep or user != GATE_USER or len(pwd) != len(GATE_KEY):
            return False
        return pwd == GATE_KEY

    async def fetch(self, request):
        if await self._authorized(request):
            return await super().fetch(request)
        return Response(
            "Unauthorized",
            status=401,
            headers={"WWW-Authenticate": f'Basic realm="{GATE_REALM}"'},
        )
`;
}

function pagesMiddleware({ key, realm }: GateInput): string {
  return `// Auto-generated by Launchpad — site access gate. Do not edit manually.
const GATE_USER = "${SITE_ACCESS_GATE_USER}";
const GATE_KEY = "${key}";
const GATE_REALM = "${escapeRealm(realm)}";
${tsCheckAuth()}
export const onRequest = async (context) => {
  if (checkAuth(context.request)) return context.next();
  return new Response("Unauthorized", {
    status: 401,
    headers: { "WWW-Authenticate": \`Basic realm="\${GATE_REALM}"\` },
  });
};
`;
}

function noopPagesMiddleware(): string {
  return `// Auto-generated by Launchpad — site access gate (disabled). Do not edit manually.
export const onRequest = async (context) => context.next();
`;
}

function gateExtension(entry: string): string {
  const ext = entry.split(".").pop()?.toLowerCase() ?? "ts";
  if (ext === "py") return "py";
  if (ext === "js") return "js";
  return "ts";
}

function withoutExt(path: string): string {
  return path.replace(/\.[^/.]*$/, "");
}

// ── Wrangler config patching ────────────────────────────────────────────────

function mainFromJsonc(content: string): string | null {
  const m = /"main"\s*:\s*"([^"]*)"/.exec(content);
  return m ? m[1] : null;
}

function mainFromToml(content: string): string | null {
  const m = /^main\s*=\s*"([^"]*)"/m.exec(content);
  return m ? m[1] : null;
}

function setMainJsonc(content: string, main: string): string {
  return content.replace(/"main"\s*:\s*"[^"]*"/, `"main": ${JSON.stringify(main)}`);
}

function setMainToml(content: string, main: string): string {
  return content.replace(/^main\s*=\s*"[^"]*"/m, `main = ${JSON.stringify(main)}`);
}

// ── Build output files ───────────────────────────────────────────────────────

export interface SiteAccessBuildResult {
  files: ScaffoldedFile[];
  gatePath: string;
  prevMain?: string;
  supported: boolean;
  reason?: string;
}

export function buildSiteAccessFiles(input: {
  templateId?: string;
  projectType: DeployTarget;
  key: string;
  realm: string;
  config?: WranglerConfigRef | null;
}): SiteAccessBuildResult {
  const unsupported = !siteAccessSupported(input.templateId);
  if (unsupported) {
    return {
      supported: false,
      files: [],
      gatePath: "",
      reason: "Site access is not supported for this template yet.",
    };
  }

  if (input.projectType === "pages") {
    return {
      supported: true,
      files: [
        {
          path: "functions/_middleware.ts",
          content: pagesMiddleware({ key: input.key, realm: input.realm }),
        },
      ],
      gatePath: "functions/_middleware.ts",
    };
  }

  const config = input.config;
  if (!config) {
    return {
      supported: false,
      files: [],
      gatePath: "",
      reason: "Could not read the repo's Wrangler config.",
    };
  }

  const currentMain =
    config.path === "wrangler.jsonc" ? mainFromJsonc(config.content) : mainFromToml(config.content);
  if (!currentMain) {
    return {
      supported: false,
      files: [],
      gatePath: "",
      reason: "Could not locate the Worker entry in the Wrangler config.",
    };
  }

  const dir = currentMain.includes("/") ? currentMain.slice(0, currentMain.lastIndexOf("/")) : ".";
  const gateName = gateExtension(currentMain) === "py" ? "launchpad_gate.py" : `launchpad-gate.${gateExtension(currentMain)}`;
  const gatePath = `${dir}/${gateName}`;

  const entryImport = withoutExt(currentMain.split("/").pop() ?? "index");
  const gateContent = (() => {
    const ui: GateInput = { key: input.key, realm: input.realm };
    if (gateExtension(currentMain) === "py") {
      return pythonGate(ui, entryImport);
    }
    if (gateExtension(currentMain) === "js") {
      return workerGateJs(ui, entryImport);
    }
    return workerGateTs(ui, entryImport);
  })();
  const gate: ScaffoldedFile = { path: gatePath, content: gateContent };

  const patched =
    config.path === "wrangler.jsonc"
      ? setMainJsonc(config.content, gatePath)
      : setMainToml(config.content, gatePath);

  return {
    supported: true,
    files: [gate, { path: config.path, content: patched }],
    gatePath,
    prevMain: currentMain,
  };
}

export function buildSiteAccessRemoval(input: {
  templateId?: string;
  projectType: DeployTarget;
  prevMain?: string;
  config?: WranglerConfigRef | null;
}): SiteAccessBuildResult {
  if (input.projectType === "pages") {
    return {
      supported: true,
      files: [{ path: "functions/_middleware.ts", content: noopPagesMiddleware() }],
      gatePath: "functions/_middleware.ts",
    };
  }

  const config = input.config;
  const prevMain = input.prevMain;
  if (!config || !prevMain) {
    return {
      supported: true,
      files: [],
      gatePath: "",
      reason: undefined,
    };
  }
  const patched =
    config.path === "wrangler.jsonc"
      ? setMainJsonc(config.content, prevMain)
      : setMainToml(config.content, prevMain);
  return { supported: true, files: [{ path: config.path, content: patched }], gatePath: "" };
}

export function siteAccessModeLabel(mode: SiteAccessMode): string {
  switch (mode) {
    case "org":
      return "Organization access";
    case "members":
      return "Members only";
    default:
      return "Public";
  }
}